Axelrod-Python/axelrod-fortran

- tests/test_player.py
I haven't used hypothesis with pytest and haven't run this but assuming
it behaves like it does for unittest this is the expected setup.
> Add basic setup for hypothesis

- tests/test_player.py
This works in a normal assertion. I haven't run it, possibly something
breaks in a test?
> Move if statement in test to assert.

- tests/test_player.py
This tests against all possible first 5 moves of a Match.
The test sets up the correct dummy history to begin the match and then
keeps track of the scores and history.
> Add a test for original_strategy

- src/axelrod_fortran/player.py
- tests/test_player.py
This might be useful given that the score is an input to the Fortran
strategies.
This is a fork of #4
> Add abilitity to play with different game

- src/axelrod_fortran/__init__.py
- src/axelrod_fortran/player.py
- tests/test_player.py
This is a fork of #5 (once #5 and #4 go in github should automatically adjust the PR).
> Add player to top namespace

- src/axelrod_fortran/player.py
- tests/test_player.py
- tests/test_titfortat.py
> Fix stochastic behavior and refactor tests to use unittest

- tests/test_player.py
I'm not using hypothesis, just looping over all basic strategies in
Axelrod. Checking that 3 matches all give the same results.
Closes #24
> Write a test for deterministic strategies.

- src/axelrod_fortran/player.py
- tests/test_player.py
Note that the test for this is a bit rubbish. I tried to mock the
`interaction_utils.compute_final_score` but couldn't get that to work.
Doing that and testing that it's called with the different game would be
the right way to test this.
Closes #16
> Change how the game is read in by the player.

- src/axelrod_fortran/player.py
- tests/test_player.py
> Add validation of original name and test

- src/axelrod_fortran/player.py
- src/axelrod_fortran/strategies.py
Also add a condition so that we only sample a random value if we know we
might need one.
Closes #25
> Change characteristics to have class as value.

- src/axelrod_fortran/strategies.py
> Mark k86r as not implemented

- src/axelrod_fortran/strategies.py
- tests/test_player.py
We don't know if these strategies are implemented are not.
See discussion on #31
> Remove assumed implementations.

- README.rst
- src/axelrod_fortran/__init__.py
- tests/test_player.py
- tests/test_titfortat.py
This aligns axelrod-fortran's api to be equivalent to axelrod's.
I've also written a very brief usage thing in the README.
> Raise namespace of strategies

- .travis.yml
- requirements.txt
> Travis Config

- .gitignore
- README.rst
- requirements.txt
- setup.py
I have also bumped the minimum requirement for Axelrod as this is the
one actually needed to reproduce Axelrod's second tournament.
Closes #41
> Update the README to use new tournament option.

- src/axelrod_fortran/strategies.py
> Add representative_strategies list

- requirements.txt
- setup.py
- src/axelrod_fortran/strategies.py
> Add implemented Gladstein for axl v3.4.0

- requirements.txt
- setup.py
- src/axelrod_fortran/strategies.py
> Add Tranquiliser as implemented strategy.

- requirements.txt
- setup.py
- src/axelrod_fortran/strategies.py
- tests/test_player.py
> Add grofman

- README.rst
- src/axelrod_fortran/player.py
- tests/test_player.py
I have also added a warning when a self interaction is being played.
Not that the warning only happens once (as indicated by the test).
I have also removed the tournament in our README.
Closes #65
> Add ability to pass shared library name to Player

- src/axelrod_fortran/strategies.py
(This is tested automatically.)
> Mark go by majority implementation

- requirements.txt
- src/axelrod_fortran/strategies.py
> Update implemented strategies

- requirements.txt
- setup.py
- src/axelrod_fortran/strategies.py
> Add latest strategies added to axelrod.

- requirements.txt
- setup.py
- src/axelrod_fortran/strategies.py
> Add strategies that are implemented in v3.11.0

- .bumpversion.cfg
- CHANGELOG.rst
- requirements.txt
- setup.py
- src/axelrod_fortran/__init__.py
- src/axelrod_fortran/strategies.py
> ** DO NOT MERGE** New Implementations

- .bumpversion.cfg
- CHANGELOG.rst
- requirements.txt
- setup.py
- src/axelrod_fortran/__init__.py
- src/axelrod_fortran/strategies.py
- Tag K66R as implemented by Mikkelson: https://github.com/Axelrod-Python/Axelrod/pull/1167
> New implementations

- requirements.txt
- setup.py
- src/axelrod_fortran/strategies.py
Closes #79.
A new release of axelrod-fortran can be done after this goes in @meatballs :+1:
> Update list of implemented strategies.
